# --------------------------------------------------------
# Docker profile ? overrides default H2 with real MySQL
# --------------------------------------------------------
spring.datasource.url=jdbc:mysql://mysql:3306/telecomdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=telecom
spring.datasource.password=telecom123

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Redis ? use container name
spring.data.redis.host=redis

# Kafka ? use container name
spring.kafka.bootstrap-servers=kafka:9092

# AI sidecar ? use container name
ai.advisor.url=http://python-sidecar:8000